# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episode',
                'ordering': ('-published_at', '-eid'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comic', '만화'), ('drama', '드라마'), ('novel', '소설')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('debut_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='work.Work'),
        ),
    ]
