# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('drama', '드라마'), ('comic', '만화'), ('novel', '소설'), ('movie', '영화')], max_length=10),
        ),
    ]
