# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20161004_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='shorten_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('novel', '소설'), ('movie', '영화'), ('comic', '만화'), ('drama', '드라마')], max_length=10),
        ),
    ]
