# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Create', 'Create'), ('Update', 'Update')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='model',
            field=models.CharField(choices=[('Record', 'Record'), ('Profile', 'Profile'), ('Episode', 'Episode'), ('Work', 'Work')], max_length=20),
        ),
    ]
