# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0003_auto_20161004_1905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Doing', 'Doing')], default='Doing', max_length=10)),
                ('episode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work.Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='work.Work')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('user', 'work', 'episode')]),
        ),
        migrations.AlterIndexTogether(
            name='record',
            index_together=set([('work', 'episode'), ('user', 'work'), ('user', 'work', 'episode')]),
        ),
    ]
